# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "marker-pdf",
# ]
# ///
"""
Convert a PDF to structured, per-section markdown files.

Usage:
    uv run pdf_to_sections.py <input.pdf> [-o OUTPUT_DIR]
    uv run pdf_to_sections.py --split-only <input.md> [-o OUTPUT_DIR]

Output structure:
    output_dir/
    ├── _metadata.md           # Title, source, section count
    ├── 00-full.md             # Complete markdown (reference copy)
    ├── 01-introduction.md     # Per-section files
    ├── 02-methods.md
    └── ...

First run will download ML models (~2GB). Subsequent runs use cache.
"""

import argparse
import os
import re
import sys
from pathlib import Path


def convert_pdf(pdf_path: str, output_dir: str) -> str:
    """Convert PDF to markdown using Marker."""
    try:
        from marker.converters.pdf import PdfConverter
        from marker.models import create_model_dict
        from marker.config.parser import ConfigParser
    except ImportError:
        print("Error: marker-pdf not available. Run with: uv run pdf_to_sections.py")
        sys.exit(1)

    print(f"Converting {pdf_path} ...")
    print("(First run downloads models. This may take a few minutes.)")

    config_parser = ConfigParser({"output_format": "markdown"})
    converter = PdfConverter(
        config=config_parser.generate_config_dict(),
        artifact_dict=create_model_dict(),
        processor_list=config_parser.get_processors(),
        renderer=config_parser.get_renderer(),
    )

    rendered = converter(pdf_path)
    markdown = rendered.markdown

    # Save full markdown
    os.makedirs(output_dir, exist_ok=True)
    full_path = os.path.join(output_dir, "00-full.md")
    with open(full_path, "w", encoding="utf-8") as f:
        f.write(markdown)

    print(f"PDF converted to markdown: {full_path}")
    return full_path


def split_markdown(md_path: str, output_dir: str) -> int:
    """Split markdown file into per-section files by top-level headings."""
    with open(md_path, "r", encoding="utf-8") as f:
        content = f.read()

    os.makedirs(output_dir, exist_ok=True)

    # Split by level-1 or level-2 headings
    # Keep the heading with its section
    parts = re.split(r"\n(?=#{1,2}\s)", content)

    sections = []
    for part in parts:
        part = part.strip()
        if not part:
            continue
        sections.append(part)

    if not sections:
        print("Warning: No sections found. Saving as single file.")
        sections = [content]

    # Extract document title from first heading
    title_match = re.match(r"#\s+(.+)", content)
    title = title_match.group(1).strip() if title_match else Path(md_path).stem

    # Write metadata
    meta_path = os.path.join(output_dir, "_metadata.md")
    with open(meta_path, "w", encoding="utf-8") as f:
        f.write(f"# {title}\n\n")
        f.write(f"- **Source**: {os.path.abspath(md_path)}\n")
        f.write(f"- **Sections**: {len(sections)}\n")
        f.write(f"- **Generated by**: pdf_to_sections.py\n")

    # Write each section
    for i, section in enumerate(sections):
        # Extract heading for filename
        heading_match = re.match(r"#{1,2}\s+(.+)", section)
        if heading_match:
            raw_title = heading_match.group(1).strip()
            safe = re.sub(r"[^\w\s-]", "", raw_title)
            safe = re.sub(r"\s+", "-", safe).strip("-")[:50].lower()
        else:
            safe = "preamble"

        filename = f"{i + 1:02d}-{safe}.md" if safe else f"{i + 1:02d}-section.md"
        filepath = os.path.join(output_dir, filename)

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(section + "\n")

    print(f"Split into {len(sections)} sections in {output_dir}/")
    return len(sections)


def main():
    parser = argparse.ArgumentParser(
        description="Convert PDF to structured markdown sections"
    )
    parser.add_argument("input", help="PDF or markdown file")
    parser.add_argument(
        "-o", "--output-dir",
        help="Output directory (default: input filename without extension)",
    )
    parser.add_argument(
        "--split-only",
        action="store_true",
        help="Skip PDF conversion, just split an existing markdown file by headings",
    )

    args = parser.parse_args()
    input_path = Path(args.input)

    if not input_path.exists():
        print(f"Error: {input_path} not found")
        sys.exit(1)

    output_dir = args.output_dir or str(input_path.with_suffix(""))

    if args.split_only or input_path.suffix.lower() in (".md", ".markdown", ".txt"):
        split_markdown(str(input_path), output_dir)
    elif input_path.suffix.lower() == ".pdf":
        md_path = convert_pdf(str(input_path), output_dir)
        split_markdown(md_path, output_dir)
    else:
        print(f"Error: Unsupported file type '{input_path.suffix}'")
        print("Supported: .pdf, .md, .markdown, .txt")
        sys.exit(1)


if __name__ == "__main__":
    main()
